name: upper-build

on:
  workflow_dispatch: # manually trigger the workflow
  push:
    paths:
      - ".github/workflows/upper-builld.yml"
      -  "upper/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: go version
