name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-builld.yml"
  #    -  "upper/**"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - run: pwd && ls -al
    - run: actions/checkout@v4
    - run: pwd && ls -al
